plugins:
  msgraph_polling_enabled:
    default: false
    validator: MsGraphPollSettingsValidator
  msgraph_polling_mailbox: ""
  msgraph_polling_client_id: ""
  msgraph_polling_tenant_id: ""
  msgraph_polling_oauth2_refresh_token:
    default: ""
    secret: true
  msgraph_polling_login_endpoint:
    default: "https://login.microsoftonline.com"
  msgraph_polling_graph_endpoint:
    default: "https://graph.microsoft.com/v1.0"